<a href="https://colab.research.google.com/github/rejinadel/Numpy-for-datascience/blob/main/basics_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array([1,5,6,9,8,7,7])
arr

array([1, 5, 6, 9, 8, 7, 7])

In [4]:
import numpy as np
arr = np.array([1,5,6,9,8,7,7])
np.append(arr,55)

array([ 1,  5,  6,  9,  8,  7,  7, 55])

In [5]:
import numpy as np
arr = np.array([1,5,6,9,8,7,7])
arr.append(51) #does'nt support in numpy array

AttributeError: ignored

In [7]:
l = [1,5,8]
l.append(6)
l #But does support to python list

[1, 5, 8, 6]

In [8]:
import numpy as np
arr = ([1,5,6,8])
np.delete(arr,1)

array([1, 6, 8])

In [9]:
import numpy as np
arr = np.array([1,5,6,9,8,7,7])
np.sort(arr)

array([1, 5, 6, 7, 7, 8, 9])

In [12]:
import numpy as np
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
import numpy as np
arr = np.arange(16)
arr
np.reshape(arr,(4,4)) #reshaping the arrays in numpy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
l = [1,2,3,4,5,6,7,8,9]
reshape = np.reshape(l,(3,3)) #reshaping in python
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
import numpy as np
arr = np.arange(20)
arr
arr = np.reshape(arr,(5,4))
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
import numpy as np
arr = np.arange(20)
arr
arr.reshape(4,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])