<a href="https://colab.research.google.com/github/rejinadel/Numpy-for-datascience/blob/main/npbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([[1,5,4],[2,4,8],[3,9,7],[8,8,8]])
arr

array([[1, 5, 4],
       [2, 4, 8],
       [3, 9, 7],
       [8, 8, 8]])

In [9]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [12]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [13]:
arr = np.linspace(start=1,stop=15,num=4)
arr

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])